# Generated by Django 2.2.7 on 2019-11-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, unique=True)),
                ('value', models.TextField()),
                ('flags', models.CharField(max_length=10)),
                ('exptime', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
